server:
  ssl:
    enabled: true
    key-store: keystore.p12
#    key-store: /home/opc/SSL/keystore.p12
    key-store-password: 156423
    key-store-type: PKCS12
    key-alias: bns-ssl
  port: 443
---

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/date
    username: root
    password: root
#    password: P@ssw0rd!

  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
      location: 'C:\IntelliJ_WorkSpace\date\src\main\resources\static\uploadImages'
---

mybatis:
  type-aliases-package: com.mat.date.model
  mapper-locations: mybatis/**/*Mapper.xml
---